[package]
name = "Furniture Catalogue"
authors = ["JosephMcKean"]
version = "2.2.0"

[dependencies]
assets = [
    "Icons/jsmk/fc/",
    "Meshes/jsmk/fc/",
    "MWSE/mods/JosephMcKean/furnitureCatalogue",
    "Sound/jsmk/fc",
    "Textures/jsmk/fc",
]

[dependencies.mwse]
buildnumber = 3251

[dependencies.mods."The Crafting Framework"]
mwse-module = "CraftingFramework"
version = "^1.12.1"
url = "https://www.nexusmods.com/morrowind/mods/51009"