[package]
name = "Furniture Catalogue"
authors = ["Amalie"]
version = "0.5"

[dependencies]
assets = [
    "MWSE/mods/JosephMcKean/furnitureCatalogue",
    "Sound/jsmk/fc",
    "Furniture Catalogue.esp",
]

[dependencies.mwse]
buildnumber = 3177

[dependencies.mods."The Crafting Framework"]
mwse-module = "CraftingFramework"
version = "^1.7.5"
url = "https://www.nexusmods.com/morrowind/mods/51009"