[package]
name = "Furniture Catalogue"
authors = [ "JosephMcKean",]
version = "0.3"

[dependencies]
assets = [ "Furniture Catalogue.esp", "MWSE/mods/JosephMcKean/furnitureCatalogue",]

[dependencies.mwse]
buildnumber = 3150

[dependencies.mge-xe]
version = ">=0.15.2"

[dependencies.mods."The Crafting Framework"]
mwse-module = "CraftingFramework"
version = "^1.6.0"
url = "https://www.nexusmods.com/morrowind/mods/51009"
