[package]
name = "Furniture Catalogue"
authors = ["Amalie"]
version = "0.8"

[dependencies]
assets = [
    "Meshes/jsmk/fc/",
    "MWSE/mods/JosephMcKean/furnitureCatalogue",
    "Sound/jsmk/fc",
    "Textures/jsmk/fc",
]

[dependencies.mwse]
buildnumber = 3182

[dependencies.mods."The Crafting Framework"]
mwse-module = "CraftingFramework"
version = "^1.7.7"
url = "https://www.nexusmods.com/morrowind/mods/51009"