[package]
name = "Furniture Catalogue"
authors = ["JosephMcKean"]
version = "0.4"

[dependencies]
assets = [
    "MWSE/mods/JosephMcKean/furnitureCatalogue",
    "Sound/jsmk/fc",
    "Furniture Catalogue.esp",
]

[dependencies.mwse]
buildnumber = 3167

[dependencies.mods."The Crafting Framework"]
mwse-module = "CraftingFramework"
version = "^1.6.0"
url = "https://www.nexusmods.com/morrowind/mods/51009"
