[package]
name = "Furniture Catalogue"
authors = ["Amalie"]
version = "1.1.2"

[dependencies]
assets = [
    "Icons/jsmk/fc/",
    "Meshes/jsmk/fc/",
    "MWSE/mods/JosephMcKean/furnitureCatalogue",
    "Sound/jsmk/fc",
    "Textures/jsmk/fc",
]

[dependencies.mwse]
buildnumber = 3209

[dependencies.mods."The Crafting Framework"]
mwse-module = "CraftingFramework"
version = "^1.8.0"
url = "https://www.nexusmods.com/morrowind/mods/51009"